---
- hosts: web
  vars_files:
    - vars.yml
    - private/vars.yml
  tasks:
  - set_fact:
      fqdn: '{{ ansible_nodename.split(".")[0] }}.{{ server_domain }}'
  - docker_container:
      name: certbot
      image: "certbot/certbot"
      network_mode: host
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt:rw
        - /var/lib/letsencrypt:/var/lib/letsencrypt:rw
        - /var/log/letsencrypt:/var/log/letsencrypt:rw
      command: 'certonly --standalone -d {{ fqdn }} -d {{ server_domain }} -d www.{{ server_domain }} --expand --force-renewal'
      detach: False
      cleanup: True
    register: certbot
  - debug: msg="{{ certbot['ansible_facts']['docker_container']['Output'].split('\n') }}"
