---
- hosts: mx
  tasks:
  - set_fact:
      fqdn: '{{ ansible_nodename.split(".")[0] }}.yottatsa.name'
  - template:
      src: dnsmasq.j2
      dest: /etc/dnsmasq.conf
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - rsyslog
    - dnsmasq
    - mutt
    - vim
    - debianutils
  - package:
      name: "{{ item }}"
      state: absent
    with_items:
    - postfix
  - file:
      path: /etc/nginx/conf.d
      state: directory
  - git:
      repo: 'https://github.com/yottatsa/postfix-mail-gateway'
      dest: /opt/postfix-mail-gateway
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/postfix-mail-gateway
     name: postfix-mail-gateway
     tag: "{{ img_rev.after }}"
  - file:
      path: /etc/postfix
      state: directory
  - template:
      src: virtual.j2
      dest: /etc/postfix/virtual
  - template:
      src: private/smime.crt
      dest: /etc/postfix/smime.crt
  - docker_container:
      name: postfix-mail-gateway
      image: "postfix-mail-gateway:{{ img_rev.after }}"
      recreate: yes
      network_mode: host
      volumes:
        - /etc/letsencrypt/live/{{ fqdn }}:/etc/postfix/ssl:ro
        - /etc/letsencrypt/archive:/etc/archive:ro
        - /dev:/dev:ro
        - /run/systemd/journal:/run/systemd/journal:ro
        - /etc/ssl:/etc/ssl:ro
        - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
        - /etc/postfix/virtual:/etc/postfix/virtual:ro
        - /etc/postfix/smime.crt:/etc/postfix/smime.crt:ro
        - /root/Maildir:/root/Maildir:rw
        - /home/yottatsa/Maildir:/home/yottatsa/Maildir:rw
  - git:
      repo: 'https://github.com/yottatsa/dovecot-mail'
      dest: /opt/dovecot-mail
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/dovecot-mail
     name: dovecot-mail
     tag: "{{ img_rev.after }}"
  - file:
      path: /etc/dovecot
      state: directory
  - template:
      src: users.j2
      dest: /etc/dovecot/users
  - docker_container:
      name: dovecot-mail
      image: "dovecot-mail:{{ img_rev.after }}"
      recreate: yes
      network_mode: host
      volumes:
        - /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem:/etc/ssl/dovecot/server.pem:ro
        - /etc/letsencrypt/live/{{ fqdn }}/privkey.pem:/etc/ssl/dovecot/server.key:ro
        - /etc/letsencrypt/archive:/etc/archive:ro
        - /dev:/dev:ro
        - /run/systemd/journal:/run/systemd/journal:ro
        - /etc/ssl:/etc/ssl:ro
        - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
        - /etc/dovecot/users:/etc/dovecot/users:ro
        - /home/yottatsa/Maildir:/home/yottatsa/Maildir:rw

