---
- hosts: mx
  vars_files:
    - vars.yml
    - private/vars.yml
  tasks:
  - set_fact:
      fqdn: '{{ ansible_nodename.split(".")[0] }}.{{ server_domain }}'
  - group:
      name: '{{ server_user }}'
      gid: 1000
  - user:
      name: '{{ server_user }}'
      group: '{{ server_user }}'
      shell: /bin/bash
      uid: 1000
  - template:
      src: dnsmasq.j2
      dest: /etc/dnsmasq.conf
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - rsyslog
    - dnsmasq
    - mutt
    - vim
    - debianutils
  - package:
      name: "{{ item }}"
      state: absent
    with_items:
    - postfix
  - file:
      path: /etc/nginx/conf.d
      state: directory
  - file:
      path: /etc/postfix
      state: directory
  - copy:
      content: |
        {{ server_domain }} {{ server_domain }}
        {% for u, p in mail_aliases.items() %}
        {{ u }}@{{ server_domain }} {{ server_user}}/Maildir{{ p }}
        {% endfor %}
      dest: /etc/postfix/virtual
  - copy:
      content: |
        {{ mail_smime }}
      dest: /etc/postfix/smime.crt
  - file:
      path: /etc/dovecot
      state: directory
  - copy:
      content: |
        {{ mail_login }}:{{ mail_password_dovecot }}:1000:1000::/home/{{ server_user }}::userdb_mail=maildir:~/Maildir
      dest: /etc/dovecot/users
  - git:
      repo: 'https://github.com/yottatsa/postfix-mail-gateway'
      dest: /opt/postfix-mail-gateway
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/postfix-mail-gateway
     name: postfix-mail-gateway
     tag: "{{ img_rev.after }}"
  - docker_container:
      name: postfix-mail-gateway
      image: "postfix-mail-gateway:{{ img_rev.after }}"
      recreate: yes
      network_mode: host
      volumes:
        - /etc/letsencrypt/live/{{ fqdn }}:/etc/postfix/ssl:ro
        - /etc/letsencrypt/archive:/etc/archive:ro
        - /dev:/dev:ro
        - /run/systemd/journal:/run/systemd/journal:ro
        - /etc/ssl:/etc/ssl:ro
        - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
        - /etc/postfix/virtual:/etc/postfix/virtual:ro
        - /etc/postfix/smime.crt:/etc/postfix/smime.crt:ro
        - /root/Maildir:/root/Maildir:rw
        - /home/{{ server_user }}/Maildir:/home/{{ server_user }}/Maildir:rw
  - git:
      repo: 'https://github.com/yottatsa/dovecot-mail'
      dest: /opt/dovecot-mail
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/dovecot-mail
     name: dovecot-mail
     tag: "{{ img_rev.after }}"
  - docker_container:
      name: dovecot-mail
      image: "dovecot-mail:{{ img_rev.after }}"
      recreate: yes
      network_mode: host
      volumes:
        - /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem:/etc/ssl/dovecot/server.pem:ro
        - /etc/letsencrypt/live/{{ fqdn }}/privkey.pem:/etc/ssl/dovecot/server.key:ro
        - /etc/letsencrypt/archive:/etc/archive:ro
        - /dev:/dev:ro
        - /run/systemd/journal:/run/systemd/journal:ro
        - /etc/ssl:/etc/ssl:ro
        - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
        - /etc/dovecot/users:/etc/dovecot/users:ro
        - /home/{{ server_user }}/Maildir:/home/{{ server_user }}/Maildir:rw
