---
- hosts: openid
  tasks:
  - git:
      repo: 'https://github.com/yottatsa/ownopenidserver'
      dest: /opt/ownopenidserver
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/ownopenidserver
     name: ownopenidserver
     tag: "{{ img_rev.after }}"
  - docker_container:
      name: ownopenidserver
      image: "ownopenidserver:{{ img_rev.after }}"
      state: started
      recreate: yes
      network_mode: host