---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
    - private/vars.yml
  tasks:
    - local_action: command hostname
      register: hostname
    - name: key
      digital_ocean:
        state: present
        command: ssh
        name: "{{ lookup('env', 'USER') }}@{{ hostname.stdout }}"
        ssh_pub_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
      register: key
    - name: instance
      digital_ocean:
        state: present
        command: droplet
        name: 'mx.{{ server_domain }}'
        size_id: 512mb
        image_id: ubuntu-16.04.2-x64
        region_id: ams2
        # Customize this for your account.
        ssh_key_ids: "{{ key.ssh_key.id }}"
        # Required for idempotence/only one droplet creation.
        unique_name: yes
        ipv6: yes
      register: do
    - add_host:
        name: "{{ do.droplet.name }}"
        groups: do, dockers, web, mx
      when: do.droplet is defined

- hosts: do
  remote_user: root
  gather_facts: false

  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"
