---
- hosts: web
  tasks:
  - docker_container:
      name: certbot
      image: "certbot/certbot"
      network_mode: host
      volumes_from:
        - nginx
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt:rw
        - /var/lib/letsencrypt:/var/lib/letsencrypt:rw
        - /var/log/letsencrypt:/var/log/letsencrypt:rw
      command: renew --webroot --force-renewal --webroot-path /var/www/yottatsa.name
      detach: False
      cleanup: True
    register: certbot
  - debug: msg="{{ certbot['ansible_facts']['docker_container']['Output'].split('\n') }}" 
