---
- hosts: all
  tasks:
  - lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: '127.0.0.1 localhost {{ ansible_nodename }}'
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - sudo
    - openssh-server
    - git
    - ca-certificates
    - iptables
  - template:
      src: firewall.j2
      dest: /etc/network/if-up.d/firewall
      mode: 0755
  - lineinfile:
      path: /etc/sudoers
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD:ALL'
  - user:
      name: yottatsa
      shell: /bin/bash
      groups: sudo
      append: yes
  - template:
      src: dnsmasq.j2
      dest: /etc/dnsmasq.conf
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - rsyslog
    - dnsmasq
    - mutt
    - vim
    - savelog
  - package:
      name: "{{ item }}"
      state: absent
    with_items:
    - postfix
  - file:
      path: /etc/nginx/conf.d
      state: directory

- hosts: dockers
  tasks:
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - docker.io
    - python3-docker
  - docker_container:
      name: ohno
      state: absent
