---
- hosts: all
  vars_files:
    - vars.yml
    - private/vars.yml
  tasks:
  - set_fact:
      hostname: '{{ ansible_nodename.split(".")[0] }}'
      fqdn: '{{ ansible_nodename.split(".")[0] }}.{{ server_domain }}'
  - hostname:
      name: '{{ fqdn }}'
  - copy:
      dest: /etc/hostname
      content: '{{ fqdn }}'
  - lineinfile:
      name: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: '127.0.1.1 {{ fqdn }} {{ hostname }}'
  - lineinfile:
      name: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: '127.0.0.1 localhost'
  - apt:
      update_cache: yes
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - make
    - mosh
    - git
    - ca-certificates
    - rsyslog-gnutls
  - service:
      name: ssh
      state: restarted
  - template:
      src: papertrail.j2
      dest: /etc/rsyslog.d/99-papertrail.conf
  - get_url:
      url: https://papertrailapp.com/tools/papertrail-bundle.pem
      dest: /etc/papertrail-bundle.pem
  - service:
      name: rsyslog
      state: restarted

- hosts: dockers
  tasks:
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - docker.io
    - python-docker
    - python3-docker
  - docker_container:
      name: ohno
      state: absent
