---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
  - set_fact:
      hostname: '{{ ansible_nodename.split(".")[0] }}'
      fqdn: '{{ ansible_nodename.split(".")[0] }}.{{ server_domain }}'
  - hostname:
      name: '{{ fqdn }}'
  - copy:
      dest: /etc/hostname
      content: '{{ fqdn }}'
  - lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: '127.0.1.1 {{ fqdn }} {{ hostname }}'
  - lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: '127.0.0.1 localhost'
  - apt:
      update_cache: yes
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - make
    - mosh
    - git
    - ca-certificates
  - service:
      name: ssh
      state: restarted

- hosts: dockers
  tasks:
  - package:
      name: "{{ item }}"
      state: latest
    with_items:
    - docker.io
    - python3-docker
  - docker_container:
      name: ohno
      state: absent
