---
- hosts: web
  tasks:
  - git:
      repo: 'https://github.com/yottatsa/ownopenidserver'
      dest: /opt/ownopenidserver
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/ownopenidserver
     name: ownopenidserver
     tag: "{{ img_rev.after }}"
  - file:
      path: /var/openidserver
      state: directory
  - docker_container:
      name: ownopenidserver
      image: "ownopenidserver:{{ img_rev.after }}"
      recreate: yes
      network_mode: host
      volumes:
        - /var/openidserver:/opt/openidserver/sstore
      state: started
      log_driver: syslog
      log_options:
        syslog-facility: daemon
        tag: ownopenidserver
  - git:
      repo: 'https://github.com/yottatsa/yottatsa.github.io'
      dest: /opt/yottatsaname
      update: yes
    register: img_rev
  - docker_image:
     path: /opt/yottatsaname
     name: yottatsaname
     tag: "{{ img_rev.after }}"
  - template:
      src: nginx-yottatsaname.j2
      dest: /etc/nginx/conf.d/10-yottatsaname.conf
  - docker_container:
      name: yottatsaname
      image: "yottatsaname:{{ img_rev.after }}"
  - template:
      src: nginx.j2
      dest: /etc/nginx/conf.d/00-nginx.conf
  - docker_container:
      name: nginx
      image: "nginx:latest"
      recreate: yes
      network_mode: host
      volumes:
        - /var/www/mx.yottatsa.name
        - /etc/letsencrypt:/etc/letsencrypt:ro
        - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      volumes_from:
        - yottatsaname
      log_driver: syslog
      log_options:
        syslog-facility: daemon
        tag: nginx
